#!/bin/bash
# vim: set filetype=bash :

# Auto SSH-ADD for commands
# Brilliant solution: http://askubuntu.com/a/27298
check-ssh-add() {
	# XXX: My system returns 'awesome'
	#if [ "$DESKTOP_SESSION" == "" ]; then
	#fi
	if [[ `ssh-add -l` != *id_?sa* ]]; then 
		echo -n '[ssh-add] '
		ssh-add -t 5h  ## 5 hour ssh-agent expiration
	fi
}


# ================================================= #
#                                                   #
#            Git / Github Simplifications           #
#                                                   #
# ================================================= #

# Check that we're ssh-added for git push.
git() {
	if [ "$1" == "push" ]; then
		check-ssh-add
	fi
	/usr/bin/git $@
}

# Shorthand/Defaults for git push
git-push() {
	dest=''
	ref=''
	if [ $# -eq 0 ]; then
		dest='github'
		ref='master'
	elif [ $# -eq 1 ]; then
		dest=$1
		ref='master'
	else
		dest=$1
		ref=$2
	fi
	echo "> Pushing to $dest the ref $ref"
	git push $dest $ref
}

# Shorthand/Defaults for git pull
git-pull() {
	dest=''
	ref=''
	if [ $# -eq 0 ]; then
		dest='github'
		ref='master'
	elif [ $# -eq 1 ]; then
		dest=$1
		ref='master'
	else
		dest=$1
		ref=$2
	fi
	echo "> Pulling from $dest the ref $ref"
	git pull $dest $ref
}

push() {
	ref=''
	if [ $# -eq 0 ]; then
		ref='master'
	else
		ref=$1
	fi
	git-push github $ref || git-push origin $ref
}


pull() {
	ref=''
	if [ $# -eq 0 ]; then
		ref='master'
	else
		ref=$1
	fi
	git-pull github $ref || git-pull origin $ref
}


# ================================================= #
#                                                   #
#                   MISCELLANEOUS                   #
#                                                   #
# ================================================= #

ssh() {
	check-ssh-add
	/usr/bin/ssh $@
}

# Molokai colorscheme for dircolors 
eval $(dircolors -b ~/.config/bash/dircolors.molokai)

# Load Xdefaults
# I've started doing this on shell spawn, because I can't seem 
# to get the login script to work correctly on multiple systems.
# TODO: Perhaps call this as a script from AwesomeWM... it doesn't
# strictly _have_ to be part of a shell init script. Think outside
# the box.
MY_CONFDIR=$HOME'/.config/bash'
MY_HOSTNAME=`uname -n` # $HOSTNAME isn't populated by this time !

xrdb -load "$MY_CONFDIR/Xdefaults"

case $MY_HOSTNAME in
	'x120e')	xrdb -merge "$MY_CONFDIR/Xdefaults.x120e";;
	'vaiop')	xrdb -merge "$MY_CONFDIR/Xdefaults.vaiop";;
	*)			echo "Invalid Hostname";;
esac

# Set the PS1 prompt to echo useful (and color-coded) info 
# Note: Colors match molokai theme!
GRAY='\e[0;38;5;245m'
BLUE='\e[1;38;5;37m'
WHITE='\e[0;38;5;255m'
PS1="\[$GRAY\]\u@\h:${debian_chroot:+($debian_chroot)}\[$BLUE\]\w\[$GRAY\]\$\[$WHITE\] "

